//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPathTeam.WpfFormCreator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WpfFormCreatorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WpfFormCreatorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPathTeam.WpfFormCreator.WpfFormCreatorResources", typeof(WpfFormCreatorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property Elements to Retrieve must be used only when the Get All Properties is set to True .
        /// </summary>
        public static string ErrorMessage_ElementsToRetrieveError {
            get {
                return ResourceManager.GetString("ErrorMessage_ElementsToRetrieveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If GetAllProperties is checked, the ElementsToRetrieve array cannot be empty..
        /// </summary>
        public static string ErrorMessage_ElementsToRetrieveMissing {
            get {
                return ResourceManager.GetString("ErrorMessage_ElementsToRetrieveMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Input Dictionary and the Elements to Retrieve cannot be both null at the same time..
        /// </summary>
        public static string ErrorMessage_EmptyInput {
            get {
                return ResourceManager.GetString("ErrorMessage_EmptyInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Form could not be launched. Internal Exception:{0}.
        /// </summary>
        public static string ErrorMessage_Generic {
            get {
                return ResourceManager.GetString("ErrorMessage_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XAML for the  StyleSheet is Invalid. This file must be a valid xaml file with a parent node of type ResourceDictionary. Internal Exception: {0}.
        /// </summary>
        public static string ErrorMessage_InvaidXAMLStyleSheet {
            get {
                return ResourceManager.GetString("ErrorMessage_InvaidXAMLStyleSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XAML mark-up provided for the Form is invalid. Make sure that the input is a valid WPF XAML form and its root element is a Grid containing the proper namespaces. Internal Exception:{0}.
        /// </summary>
        public static string ErrorMessage_InvalidFormXAML {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidFormXAML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If GetAllProperties is unchecked, the Inputs dictionary cannot be empty.
        /// </summary>
        public static string ErrorMessage_NoInputGiven {
            get {
                return ResourceManager.GetString("ErrorMessage_NoInputGiven", resourceCulture);
            }
        }
    }
}
